# Android Emulator Configuration
android_enabled: true
android_base_dir: "/opt/android-emulator"

# Appium Configuration
appium_port: 4723

# Android Emulator Configuration
android_platform_version: "13"
android_api_level: "33"
android_device: "pixel_6"

# Docker image - redroid (для Ubuntu 24.04)
android_emulator_image: "redroid/redroid"
android_emulator_tag: "13.0.0-latest"

# Альтернативные варианты:
# android_emulator_tag: "latest"  # Android 14
# android_emulator_tag: "12.0.0"  # Android 12
# android_emulator_tag: "11.0.0"  # Android 11

# Emulator hardware config
emulator_ram: "2048"
emulator_vm_heap: "256"
emulator_disk_size: "4000M"
emulator_gpu: "swiftshader_indirect"
android_container_mem_limit: "3g"
android_container_cpu_limit: "2"

# Redroid specific options для Ubuntu 24.04
redroid_opts: "androidboot.redroid_gpu_mode=guest androidboot.redroid_memfd=true androidboot.redroid_width=1080 androidboot.redroid_height=1920 androidboot.redroid_dpi=480"

# Test app configuration
test_app_name: "wishlist-349317-5fd795.apk"
test_app_source: "{{ playbook_dir }}/files/{{ test_app_name }}"
test_app_destination: "{{ android_apps_dir }}/{{ test_app_name }}"
test_app_package: "ru.otus.wishlist"

# VNC Configuration
vnc_port: 6080

# Network
docker_network_name: "selenoid_network"