---
- name: Create folder with stubs
  file:
    path: "/home/{{ username }}/wiremock/stubs"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0666"

- name: Rendering stub template
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ username }}/wiremock/stubs/{{ item }}"
  loop:
    - user_get_all.json
    - user_get_by_id.json
    - course_get_all.json
    - user_soap.json