[selenoid]
109.73.196.103

[selenoid:vars]
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Jenkins variables
jenkins_port=8090
jenkins_agent_port=50001

# Android Emulator variables
android_enabled=true
appium_port=4723
android_platform_version=34
test_app_name=app-debug.apk

; test_app_source=/local/path/to/your/app-debug.apk
; test_app_source={{ playbook_dir }}/files/wishlist-349317-5fd795.apk