---
- name: Deploy Selenoid with VNC, Selenoid UI and Android Emulator
  hosts: selenoid
  become: yes
  gather_facts: yes

  tasks:
    - name: Create Docker network for all containers
      docker_network:
        name: "{{ docker_network_name }}"
        state: present
        driver: bridge
      when: ansible_os_family == "Debian"
      tags:
        - always
        - network

    - name: Ensure KVM permissions
      file:
        path: /dev/kvm
        mode: "0666"
      when: ansible_os_family == "Debian"
      tags:
        - always
        - android
        - kvm

  roles:
    - role: docker_setup
      tags:
        - docker
        - docker_setup
        - always

    - role: selenoid
      tags:
        - selenoid
        - browsers
        - ggr
        - web

    - role: android_emulator
      tags:
        - android
        - android_emulator
        - appium
        - mobile

    - role: jenkins
      tags:
        - jenkins
        - ci
        - pipeline